### PR TITLE
fix: register name in k210 definition

### PR DESCRIPTION
**Pull request by yannishuber**

### CODE REVIEW

**Comment by deadprogram** [comment]
Hello @yannishuber can you please rebase this PR against master now that I merged the other PR bringing the repo up to date? Thank you.

**Comment by deadprogram** [comment]
Thanks @yannishuber now merging.

**Comment by aykevl** [comment]
It may be better to keep the master branch equal to the master branch of posborne/cmsis-svd and merge hotfixes (like these) in a branch. That will allow a smooth transition when the PR has been merged upstream:

1. Create hotfix (like this) in a branch.
2. Switch tinygo repo over to use the commit in that branch. This works, because git submodules simply pull a particular git commit ignoring branch names (but of course the upstream URL must be correct otherwise it couldn't find the commit).
3. Once the fix lands in posborne/cmsis-svd, fast-forward merge the changes in our master branch.
4. Switch tinygo dev branch back over to our cmsis-dev master. The tinygo master branch will continue working, as it will pull the older version of the commit from the branch.

**Comment by yannishuber** [comment]
@aykevl Ok, I tought you suggested to completely switch to the TinyGo fork of cmsis-svd in comment https://github.com/tinygo-org/tinygo/pull/1149#pullrequestreview-424872859. But sure, I can revert the master branch and create a new pull request on a new branch.

**Comment by deadprogram** [comment]
@aykevl that procedure is a little too complicated IMO. We can always force push the posborne fork over the tinygo one, if we want to to get completely in sync, and we do not have to go thru quite so many git gymnastics.

**Comment by aykevl** [comment]
That would work, as long as we keep the current master commit (032744910b4cbda062832c209e58ff00e7671e92) in a branch somewhere so that older TinyGo revisions won't break (after the master branch is force-pushed).

**Pull request merged**
