### PR TITLE
Add SVD file for the ATSAME5x

### PR DESCRIPTION
**Pull request by sago35**
for support atsame54-xpro and feather-m4-can.

* https://www.microchip.com/developmenttools/productdetails/atsame54-xpro
* https://www.adafruit.com/product/4759

----

SVD file source:
http://packs.download.atmel.com/

* Atmel SAME51 Series Device Support (1.1.139)
* Atmel SAME53 Series Device Support (1.1.118)
* Atmel SAME54 Series Device Support (1.1.134)

All these files are Apache 2.0 direct from the vendor.

### CODE REVIEW

**Comment by aykevl** [comment]
@sago35 can you please submit this PR to the upstream repository at https://github.com/posborne/cmsis-svd?

**Comment by sago35** [comment]
I have created a pull request as follows
https://github.com/posborne/cmsis-svd/pull/126

**Comment by aykevl** [comment]
Thank you!

**Comment by sago35** [comment]
@aykevl @deadprogram 
I'd like to add the atsame5x series to tinygo-org/tinygo soon.
posborne/cmsis-svd has no response so far.

So I would like to proceed as follows.

1. merge this PR
2. modify the make gen-device-svd-sam / gitmodule configuration in tinygo-org/tinygo

**Comment by deadprogram** [comment]
Merging in order to resolve until upstream repo includes this.

**Pull request merged**
